{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9bc224e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark import SparkConf\n",
    "from pyspark.sql import SparkSession\n",
    "from pyspark.sql.functions import col, avg, sum as sum_, first, round, min, when, lit, to_date, to_timestamp, date_format, hour\n",
    "from pyspark.sql.types import DoubleType, IntegerType, StringType, DateType, TimestampType"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4c8d8adc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: boto3 in /usr/local/lib/python3.7/site-packages (1.33.13)\n",
      "Requirement already satisfied: pandas in /usr/local/lib64/python3.7/site-packages (1.3.5)\n",
      "Requirement already satisfied: botocore<1.34.0,>=1.33.13 in /usr/local/lib/python3.7/site-packages (from boto3) (1.33.13)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.7/site-packages (from boto3) (1.0.1)\n",
      "Requirement already satisfied: s3transfer<0.9.0,>=0.8.2 in /usr/local/lib/python3.7/site-packages (from boto3) (0.8.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib64/python3.7/site-packages (from pandas) (1.21.6)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.7/site-packages (from botocore<1.34.0,>=1.33.13->boto3) (1.26.20)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.17.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/site-packages/boto3/compat.py:82: PythonDeprecationWarning: Boto3 will no longer support Python 3.7 starting December 13, 2023. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.8 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/\n",
      "  warnings.warn(warning, PythonDeprecationWarning)\n"
     ]
    }
   ],
   "source": [
    "!pip install boto3 pandas\n",
    "\n",
    "import boto3\n",
    "import pandas as pd\n",
    "import io\n",
    "\n",
    "s3_output_path = 's3a://bucket-raw-upa-connect-eduardo/tabela_historico_sensor.csv'\n",
    "\n",
    "csv_files = [\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_20.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_21.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_22.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_23.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_24.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_25.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_26.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_27.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_28.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_29.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_30.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_05_31.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_06_01.csv',\n",
    "    'bucket-raw-upa-connect-eduardo/dados_2025_06_02.csv'\n",
    "]\n",
    "\n",
    "\n",
    "# Inicializa o cliente S3\n",
    "s3_client = boto3.client('s3')\n",
    "\n",
    "# Lista para armazenar os DataFrames\n",
    "dfs = []\n",
    "\n",
    "for file in csv_files:\n",
    "    bucket_name, key = file.split('/', 1)\n",
    "    \n",
    "    # Faz o download do arquivo\n",
    "    response = s3_client.get_object(Bucket=bucket_name, Key=key)\n",
    "    \n",
    "    # Lê o CSV diretamente do objeto S3 (response['Body'] é um StreamingBody)\n",
    "    df = pd.read_csv(io.BytesIO(response['Body'].read()))\n",
    "    \n",
    "    dfs.append(df)\n",
    "\n",
    "# Concatena todos os DataFrames em um só\n",
    "df_final = pd.concat(dfs, ignore_index=True)\n",
    "df_final['data_hora'] = pd.to_datetime(df_final['data_hora'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "659813ad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ":: loading settings :: url = jar:file:/usr/local/lib/python3.7/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Ivy Default Cache set to: /root/.ivy2/cache\n",
      "The jars for the packages stored in: /root/.ivy2/jars\n",
      "org.apache.hadoop#hadoop-aws added as a dependency\n",
      "com.amazonaws#aws-java-sdk-bundle added as a dependency\n",
      ":: resolving dependencies :: org.apache.spark#spark-submit-parent-a9710dcd-7584-416a-992b-570880f7e1f9;1.0\n",
      "\tconfs: [default]\n",
      "\tfound org.apache.hadoop#hadoop-aws;3.3.4 in central\n",
      "\tfound com.amazonaws#aws-java-sdk-bundle;1.12.262 in central\n",
      "\tfound org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central\n",
      ":: resolution report :: resolve 506ms :: artifacts dl 22ms\n",
      "\t:: modules in use:\n",
      "\tcom.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]\n",
      "\torg.apache.hadoop#hadoop-aws;3.3.4 from central in [default]\n",
      "\torg.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]\n",
      "\t:: evicted modules:\n",
      "\tcom.amazonaws#aws-java-sdk-bundle;1.11.901 by [com.amazonaws#aws-java-sdk-bundle;1.12.262] in [default]\n",
      "\t---------------------------------------------------------------------\n",
      "\t|                  |            modules            ||   artifacts   |\n",
      "\t|       conf       | number| search|dwnlded|evicted|| number|dwnlded|\n",
      "\t---------------------------------------------------------------------\n",
      "\t|      default     |   4   |   0   |   0   |   1   ||   3   |   0   |\n",
      "\t---------------------------------------------------------------------\n",
      ":: retrieving :: org.apache.spark#spark-submit-parent-a9710dcd-7584-416a-992b-570880f7e1f9\n",
      "\tconfs: [default]\n",
      "\t0 artifacts copied, 3 already retrieved (0kB/14ms)\n",
      "25/06/10 23:37:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable\n",
      "Setting default log level to \"WARN\".\n",
      "To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).\n",
      "/usr/local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.\n",
      "  warnings.warn(\"Python 3.7 support is deprecated in Spark 3.4.\", FutureWarning)\n"
     ]
    }
   ],
   "source": [
    "# Configurações do Spark\n",
    "conf = SparkConf()\n",
    "conf.set('spark.jars.packages', 'org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.11.901')\n",
    "conf.set('spark.hadoop.fs.s3a.aws.credentials.provider', 'com.amazonaws.auth.InstanceProfileCredentialsProvider')\n",
    "\n",
    "# Criar sessão Spark\n",
    "spark = SparkSession.builder.config(conf=conf).getOrCreate()\n",
    "\n",
    "TabelaCompleta = spark.createDataFrame(df_final)\n",
    "\n",
    "df_camera = TabelaCompleta.filter(\n",
    "    (col(\"fk_sensor\") == 1)\n",
    ").filter(col(\"valor\").isNotNull())\n",
    "\n",
    "\n",
    "df_camera_filtrado = df_camera.withColumn(\"data_hora\", to_timestamp(col(\"data_hora\"), \"yyyy-MM-dd HH:mm:ss\")) \\\n",
    "    .withColumn(\"qtde_pessoas\", col(\"valor\").cast(IntegerType())) \\\n",
    "    .withColumn(\"fk_upa\", col(\"fk_upa\").cast(IntegerType())) \\\n",
    "    .drop(\"valor\") \\\n",
    "    .drop(\"fk_unid_medida\") \\\n",
    "    .drop(\"fk_paciente\") \\\n",
    "    .drop(\"fk_sensor\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cb16988c",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_camera_filtrado = df_camera_filtrado.filter(\n",
    "        (col(\"qtde_pessoas\") >= 0) & (col(\"qtde_pessoas\") <= 200)\n",
    "    ) \\\n",
    "    .orderBy(col(\"fk_upa\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "41349ec0",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_final_semanal = df_camera_filtrado.withColumn(\"data\", to_date(col(\"data_hora\"))) \\\n",
    "                .drop(\"data_hora\")  \n",
    "\n",
    "df_final_semanal = df_final_semanal.groupBy('data', 'fk_upa').agg(\n",
    "    avg('qtde_pessoas').cast(IntegerType()).alias('media_pessoas')\n",
    ").orderBy('fk_upa', 'data')\n",
    "\n",
    "\n",
    "df_final_diario = df_camera_filtrado.withColumn(\"data\", to_date(col(\"data_hora\"))) \\\n",
    "                .withColumn(\"hora\", hour(col(\"data_hora\"))) \\\n",
    "                .drop(\"data_hora\")                \n",
    "\n",
    "df_final_diario = df_final_diario.groupBy('data', 'hora', 'fk_upa').agg(\n",
    "    avg('qtde_pessoas').cast(IntegerType()).alias('media_pessoas')\n",
    ").orderBy('fk_upa', 'data', 'hora')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "dd3969b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Baixando credenciais do S3: s3://bucket-trusted-upa-connect-eduardo/credenciais.json para /tmp/credenciais.json...\n",
      "Credenciais baixadas com sucesso.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/site-packages/boto3/compat.py:82: PythonDeprecationWarning: Boto3 will no longer support Python 3.7 starting December 13, 2023. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.8 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/\n",
      "  warnings.warn(warning, PythonDeprecationWarning)\n"
     ]
    }
   ],
   "source": [
    "import boto3\n",
    "\n",
    "S3_BUCKET_CREDENTIALS = 'bucket-trusted-upa-connect-eduardo'\n",
    "S3_KEY_CREDENTIALS = 'credenciais.json'\n",
    "LOCAL_CREDENTIALS_PATH = '/tmp/credenciais.json'\n",
    "\n",
    "print(f\"Baixando credenciais do S3: s3://{S3_BUCKET_CREDENTIALS}/{S3_KEY_CREDENTIALS} para {LOCAL_CREDENTIALS_PATH}...\")\n",
    "s3 = boto3.client('s3')\n",
    "try:\n",
    "    s3.download_file(S3_BUCKET_CREDENTIALS, S3_KEY_CREDENTIALS, LOCAL_CREDENTIALS_PATH)\n",
    "    print(\"Credenciais baixadas com sucesso.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao baixar credenciais do S3: {e}\")\n",
    "    sys.exit(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "de185c37",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in /usr/local/lib64/python3.7/site-packages (1.3.5)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib64/python3.7/site-packages (from pandas) (1.21.6)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.17.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'pandas' instalado com sucesso.\n",
      "Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.7/site-packages (1.2.2)\n",
      "Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.7/site-packages (from google-auth-oauthlib) (2.40.2)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/site-packages (from google-auth-oauthlib) (2.0.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (5.5.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/site-packages (from google-auth>=2.15.0->google-auth-oauthlib) (4.9.1)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)\n",
      "Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.31.0)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-auth-oauthlib) (0.5.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2025.4.26)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'google-auth-oauthlib' instalado com sucesso.\n",
      "Found existing installation: gspread 3.7.0\n",
      "Uninstalling gspread-3.7.0:\n",
      "  Successfully uninstalled gspread-3.7.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting gspread==3.7.0\n",
      "  Using cached gspread-3.7.0-py3-none-any.whl.metadata (1.9 kB)\n",
      "Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.7/site-packages (from gspread==3.7.0) (2.40.2)\n",
      "Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.7/site-packages (from gspread==3.7.0) (1.2.2)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread==3.7.0) (5.5.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread==3.7.0) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/site-packages (from google-auth>=1.12.0->gspread==3.7.0) (4.9.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/site-packages (from google-auth-oauthlib>=0.4.1->gspread==3.7.0) (2.0.0)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread==3.7.0) (0.5.1)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (3.2.2)\n",
      "Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (2.31.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.7.0) (2025.4.26)\n",
      "Using cached gspread-3.7.0-py3-none-any.whl (28 kB)\n",
      "Installing collected packages: gspread\n",
      "Successfully installed gspread-3.7.0\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mDataFrame Spark convertido para Pandas com sucesso.\n",
      "Aba 'VisaoComputacionalSemanal' encontrada e limpa.\n",
      "Dados do DataFrame final enviados com sucesso para a aba 'VisaoComputacionalSemanal'.\n",
      "Aba 'VisaoComputacionalDiario' encontrada e limpa.\n",
      "Dados do DataFrame final enviados com sucesso para a aba 'VisaoComputacionalDiario'.\n",
      "Arquivo de credenciais temporário '/tmp/credenciais.json' removido.\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "import sys\n",
    "\n",
    "def install_package(package):\n",
    "    try:\n",
    "        subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", package])\n",
    "        print(f\"'{package}' instalado com sucesso.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Erro ao instalar '{package}': {e}\")\n",
    "\n",
    "# Instalar as bibliotecas necessárias\n",
    "install_package(\"pandas\")\n",
    "install_package(\"google-auth-oauthlib\")\n",
    "\n",
    "!pip uninstall gspread -y\n",
    "!pip install gspread==3.7.0\n",
    "\n",
    "import pandas as pd\n",
    "import gspread\n",
    "from google.oauth2.service_account import Credentials\n",
    "import os\n",
    "import sys\n",
    "\n",
    "GOOGLE_SHEET_ID = '1i6BfuZXPOcTp6BFAiVkpktOBym0HtakZacUKfDzu1zI'\n",
    "\n",
    "\n",
    "# === AUTENTICAÇÃO GOOGLE ===\n",
    "\n",
    "\n",
    "scopes = [\"https://www.googleapis.com/auth/spreadsheets\", \"https://www.googleapis.com/auth/drive\"]\n",
    "credenciais = Credentials.from_service_account_file(LOCAL_CREDENTIALS_PATH, scopes=scopes)\n",
    "cliente = gspread.authorize(credenciais)\n",
    "planilha = cliente.open_by_key(GOOGLE_SHEET_ID)\n",
    "\n",
    "# === ENVIA O DATAFRAME FINAL PARA A NOVA ABA \"teste\" ===\n",
    "NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL = \"VisaoComputacionalSemanal\"\n",
    "NOME_ABA_VISAO_COMPUTACIONAL_DIARIO = \"VisaoComputacionalDiario\"\n",
    "\n",
    "# Converter Spark DataFrame para Pandas DataFrame\n",
    "try:\n",
    "    df_pandas_semanal = df_final_semanal.toPandas()\n",
    "    df_pandas_diario = df_final_diario.toPandas()\n",
    "    print(\"DataFrame Spark convertido para Pandas com sucesso.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao converter Spark DataFrame para Pandas: {e}\")\n",
    "    print(\"O DataFrame pode ser muito grande para a memória do driver ou a sessão Spark está inválida.\")\n",
    "    sys.exit(1)\n",
    "\n",
    "# --- NOVO TRECHO: Ajustar tipagem das colunas para o Google Sheets ---\n",
    "# Apenas formata colunas de data/hora para string ISO 8601.\n",
    "# As demais colunas (numéricas, strings, etc.) são mantidas em seus tipos nativos no Pandas.\n",
    "# O gspread e o Google Sheets farão a inferência de tipo para elas.\n",
    "\n",
    "# Coluna 'data_chegada': assegurar que é string DD/MM/YYYY\n",
    "if 'data' in df_pandas_semanal.columns:\n",
    "    if pd.api.types.is_datetime64_any_dtype(df_pandas_semanal['data']):\n",
    "        df_pandas_semanal['data'] = df_pandas_semanal['data'].dt.strftime('%d/%m/%Y') # <-- MUDANÇA AQUI\n",
    "    elif pd.api.types.is_string_dtype(df_pandas_semanal['data']):\n",
    "        # Tentar converter strings que podem não estar em formato padrão para datetime,\n",
    "        # e depois formatar para DD/MM/YYYY. 'errors=coerce' transforma não-datas em NaT.\n",
    "        df_pandas_semanal['data'] = pd.to_datetime(df_pandas_semanal['data'], errors='coerce').dt.strftime('%d/%m/%Y') # <-- MUDANÇA AQUI\n",
    "    # Preencher valores nulos (NaT) com string vazia, pois None também pode causar problemas.\n",
    "    df_pandas_semanal['data'] = df_pandas_semanal['data'].fillna('')\n",
    "    \n",
    "# Coluna 'data_chegada': assegurar que é string DD/MM/YYYY\n",
    "if 'data' in df_pandas_diario.columns:\n",
    "    if pd.api.types.is_datetime64_any_dtype(df_pandas_diario['data']):\n",
    "        df_pandas_diario['data'] = df_pandas_diario['data'].dt.strftime('%d/%m/%Y') # <-- MUDANÇA AQUI\n",
    "    elif pd.api.types.is_string_dtype(df_pandas_diario['data']):\n",
    "        # Tentar converter strings que podem não estar em formato padrão para datetime,\n",
    "        # e depois formatar para DD/MM/YYYY. 'errors=coerce' transforma não-datas em NaT.\n",
    "        df_pandas_diario['data'] = pd.to_datetime(df_pandas_diario['data'], errors='coerce').dt.strftime('%d/%m/%Y') # <-- MUDANÇA AQUI\n",
    "    # Preencher valores nulos (NaT) com string vazia, pois None também pode causar problemas.\n",
    "    df_pandas_diario['data'] = df_pandas_diario['data'].fillna('')\n",
    "\n",
    "    \n",
    "dados_semanais = [df_pandas_semanal.columns.tolist()] + df_pandas_semanal.values.tolist()\n",
    "dados_diarios = [df_pandas_diario.columns.tolist()] + df_pandas_diario.values.tolist()\n",
    "\n",
    "try:\n",
    "    aba = planilha.worksheet(NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL)\n",
    "    aba.clear()\n",
    "    print(f\"Aba '{NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL}' encontrada e limpa.\")\n",
    "except gspread.exceptions.WorksheetNotFound:\n",
    "    aba = planilha.add_worksheet(title=NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL, rows=str(len(dados_semanais) + 100), cols=str(len(df_pandas_semanal.columns) + 10))\n",
    "    print(f\"Aba '{NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL}' criada.\")\n",
    "\n",
    "try:\n",
    "    aba.update(dados_semanais)\n",
    "    print(f\"Dados do DataFrame final enviados com sucesso para a aba '{NOME_ABA_VISAO_COMPUTACIONAL_SEMANAL}'.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao atualizar a aba do Google Sheets: {e}\")\n",
    "\n",
    "    \n",
    "try:\n",
    "    aba = planilha.worksheet(NOME_ABA_VISAO_COMPUTACIONAL_DIARIO)\n",
    "    aba.clear()\n",
    "    print(f\"Aba '{NOME_ABA_VISAO_COMPUTACIONAL_DIARIO}' encontrada e limpa.\")\n",
    "except gspread.exceptions.WorksheetNotFound:\n",
    "    aba = planilha.add_worksheet(title=NOME_ABA_VISAO_COMPUTACIONAL_DIARIO, rows=str(len(dados_diarios) + 100), cols=str(len(df_pandas_semanal.columns) + 10))\n",
    "    print(f\"Aba '{NOME_ABA_VISAO_COMPUTACIONAL_DIARIO}' criada.\")\n",
    "\n",
    "try:\n",
    "    aba.update(dados_diarios)\n",
    "    print(f\"Dados do DataFrame final enviados com sucesso para a aba '{NOME_ABA_VISAO_COMPUTACIONAL_DIARIO}'.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao atualizar a aba do Google Sheets: {e}\")\n",
    "\n",
    "# Opcional: Remover o arquivo de credenciais temporário\n",
    "if os.path.exists(LOCAL_CREDENTIALS_PATH):\n",
    "    os.remove(LOCAL_CREDENTIALS_PATH)\n",
    "    print(f\"Arquivo de credenciais temporário '{LOCAL_CREDENTIALS_PATH}' removido.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec117a47",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
